### ISSUE TITLE
Makefile for OpenWrt 

### ISSUE THREAD

**Issue by LGA1150** [Chion82/netfilter-full-cone-nat#10]
能否提供集成到 OpenWrt 的 Makefile？目前我通过 patch 直接集成到内核里去，不太方便
kmod-ipt-fullconenat 对应 内核模块 xt_FULLCONENAT.ko
iptables-mod-fullconenat 对应 iptables 扩展 libipt_FULLCONENAT.so

**Comment by Chion82** [comment]
最好是封装成一个内核模块 package 。但是鉴于大多数 OpenWRT 内核编译参数没有开启 `CONFIG_NF_CONNTRACK_EVENTS` ，可能免不了需要同时重新编译多个 netfilter 子系统模块。
现在我暂未有可用的 OpenWRT 开发调试环境，希望有心人士可以帮忙跟进。

**Comment by LGA1150** [comment]
http://www.right.com.cn/forum/thread-319827-1-1.html 这是我写的，是通过 patch 直接集成到内核与 iptables 里去
Makefile 可以参考 https://github.com/openwrt-develop/ndpi-netfilter/blob/master/Makefile

**Comment by LGA1150** [comment]
https://github.com/LGA1150/openwrt-fullconenat

**Comment by Chion82** [comment]
@LGA1150 感谢。链接已添加到 README 。
