### ISSUE TITLE
可能由网卡驱动兼容问题导致的自动重启

### ISSUE THREAD

**Issue by ZhYuLn** [Chion82/netfilter-full-cone-nat#11]
@Chion82 您好，我在编译了最新的版本后，在服务器上跑了两天，发现服务器会出现自动重启的问题。经过一段时间的排查之后，发现网卡驱动那边会有bug，不过具体的bug信息我这边并不是特别多，我这边的debug信息不是很多，我附上一段看下对您这边是否有帮助。
![debug](https://user-images.githubusercontent.com/38172095/39968871-617c080a-5706-11e8-8037-7c09c4f54a10.png)

**Comment by Chion82** [comment]
这一小段 Call Trace 还看不出来是什么问题，甚至都不在本模块的调用栈中。如果能提供更多的内核调试信息会更加方便，通过编译内核时打开多一些debug参数会很有帮助（特别是死锁检测部分，上个bug是死锁问题）。

如果确认是网卡驱动的bug，其实我这边也没有什么好的解决方案，建议多更换几个内核版本试试。

**Comment by ZhYuLn** [comment]
嗯，好的，我这边换个内核试试。您这边有推荐使用的内核版本么。

**Comment by Chion82** [comment]
@ZhYuLn 更换内核后问题是否解决？

**Comment by ZhYuLn** [comment]
@Chion82 更换完内核暂时没有什么问题，不过更多的信息可能得需要再观察一段时间才能够确定是否能够在当前内核下稳定运行。我这段时间会收集下系统的一些信息，如果有问题，并且能收集到一些有价值的信息的话我再提交给您，到时候再麻烦您进一步优化下。

**Comment by Chion82** [comment]
先 close ，有进一步信息确定是本模块问题时再跟进。
