### ISSUE TITLE
This is openwrt's official implementation of Full Cone Nat

### ISSUE THREAD

**Issue by 873578156** [Chion82/netfilter-full-cone-nat#24]
这是openwrt官方给的实现Full Cone Nat方案：如果要实现Full Cone Nat，只要在启动项中把firewall先disable，然后在close就可以了。不显示Full Cone Net原因是Windows防火墙没关。
This is openwrt's official implementation of Full Cone Nat: to implement Full Cone Nat, disable the firewall in the enable menu and close it. Full Cone Net is not displayed because Windows firewall is not off.

**Comment by LGA1150** [comment]
来源请求
