### ISSUE TITLE
centos 7.6 insmod报Unknown symbol in module

### ISSUE THREAD

**Issue by PHCSJC** [Chion82/netfilter-full-cone-nat#25]
环境：centos 7 x86_64
内核：Linux localhost.localdomain 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

编译没有报错，insmod时报错：
insmod xt_FULLCONENAT.ko
insmod: ERROR: could not insert module xt_FULLCONENAT.ko: Unknown symbol in module

dmesg里显示：
[ 2290.786104] xt_FULLCONENAT: Unknown symbol nf_conntrack_find_get (err 0)
[ 2290.786126] xt_FULLCONENAT: Unknown symbol nf_conntrack_register_notifier (err 0)
[ 2290.786187] xt_FULLCONENAT: Unknown symbol nf_conntrack_unregister_notifier (err 0)
[ 2290.786212] xt_FULLCONENAT: Unknown symbol nf_nat_setup_info (err 0)

大佬看看是什么原因呢？

**Comment by Chion82** [comment]
This full-cone-nat module depends on NAT and other basic netfilter modules.
Try to load dependencies with `modprobe nf_nat` before running `insmod`.

**Comment by PHCSJC** [comment]
good, it is ok , FullCone NAT can normal work.
Thanks!
Thumb up for you!

**Comment by PHCSJC** [comment]
大佬，再来请教了，我在armbian上编译的，也编译成功了，但insmod提示下面的错误：
insmod xt_FULLCONENAT.ko 
insmod: ERROR: could not insert module xt_FULLCONENAT.ko: Invalid module format

把这个模块复制到/lib/modules/`uname -r`/kernel/net/ipv4/netfilter/，depmod -a 建立的依赖关系，modprobe还是报这个错误。
modprobe xt_FULLCONENAT
modprobe: ERROR: could not insert 'xt_FULLCONENAT': Exec format error

系统是armbian，aarch64，内核是5.0.2，硬件是斐讯N1。

下面是模块的属性
file xt_FULLCONENAT.ko
xt_FULLCONENAT.ko: ELF 64-bit LSB relocatable, ARM aarch64, version 1 (SYSV), BuildID[sha1]=75b0c3f90ac0d09d8bf4e0f93b60d44e78e93ddf, not stripped

大佬帮看看是什么原因呢？thanks!

**Comment by PHCSJC** [comment]
It is be sloved,because kernel source version is error,sorry,my reason!

**Comment by PHCSJC** [comment]
Hi，fullcone nat can be used in single-arm routing?
yesterday,I success compiler and install fullcone nat in Centos7,It's very surprise.
and today,I continue test in my N1(armbian aarch64 kernel 5.0.2), and I have comiler model and iptables,and I can use iptables with FULLCONENAT,but I test nat also is PortRestrictedCone.
so I think this reason maybe  my n1 is a single-arm routing
so fullcone nat whether support single-arm routing?
thanks!
