### ISSUE TITLE
运行一段时间后系统会死机

### ISSUE THREAD

**Issue by qibinghua** [Chion82/netfilter-full-cone-nat#8]
centos 6 x64位 阿里云
一段时间后死机， 然后系统也没有记录日志。
你有联系方式吗？ 可以付费请解决这个问题

**Comment by Chion82** [comment]
@qibinghua 请确认是“死机”（kernel BUG/kernel panic），抑或是网络子系统崩溃导致无法ssh。
可以尝试在阿里云的网页控制台上登录tty1，保持运行 `dmesg -wH` 。
当发生内核错误导致死机之前，错误日志会打印到tty1。
这时候进入网页控制台应该能看到tty1上的错误信息。请提供这些关键的信息。

另外，如果是由于 conntrack table full 导致的网络崩溃，该BUG已修复，请拉取最新的代码重新编译，参考 #7

**Comment by qibinghua** [comment]
可以给一个联系方式我吗? 我付费请你做一点优化?

**Comment by qibinghua** [comment]
昨天截图的错误信息在这里
http://poland02.cat.la/error.jpg

**Comment by qibinghua** [comment]
同事说系统完全进不去的. 只能截图到这个. 代码是最新的代码的. 望能留给联系方式

**Comment by Chion82** [comment]
已确认该BUG，是本模块中GC回调被抢占所致。
已初步修复，在 [hotfix/event_cb_deadlock](https://github.com/Chion82/netfilter-full-cone-nat/tree/hotfix/event_cb_deadlock) 分支中持续更新和测试。

**Comment by Chion82** [comment]
fixed
